spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DB_PAGE?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
