spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DB_PAGE?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

sendgrid:
  api_key: SENDGRID_API_KEY
  from: SENDGRID_FROM_EMAIL
